### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by MSP-Greg**
Add documentation based on puma tag v3.12.1, updates http refs to https

### CODE REVIEW

**Comment by dentarg** [comment]
@MSP-Greg do you want to add documentation somewhere how you generated these HTML files?

**Comment by MSP-Greg** [comment]
@dentarg

See [Puma issue 1743](https://github.com/puma/puma/issues/1743).

I've got docs for several versions of Ruby & several gems (most are based on master branch) at:

https://msp-greg.github.io/

The docs were generated by an 'enhanced' YARD plugin that I started working on several years ago, which started as simply an 'I want this to work on a tablet' project.  At present, I haven't released it yet.

**Comment by nateberkopec** [comment]
@MSP-Greg want to re-run this again for 4.1?

**Comment by MSP-Greg** [comment]
Yes, I can.  Let me see where I put that script...   Might be later.

**Pull request merged**
